[package]
name = "legendre-sqnum"
version = "0.1.0"
authors = ["quickshell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitset-core = "0.1.1"
rand = "0.7"
rayon = "1.1"
charts = "0.3.0"